### ISSUE TITLE
Floorplan API todos

### ISSUE THREAD

**Issue by nmoroze** [siliconcompiler/siliconcompiler#239]
Creating one top-level issue to track and prioritize all the things to get the Floorplan API into a finished state (could also make this a Github project w/ individual issues for each item, but I'll try this approach out). 

Critical path:
- [x] Update PR #228 to eliminate distinctions between how I/O cells and macros are handled
- [x] Clean up padring tests (replace three tests in file with one separate test that replicates Yosys padring gen example)
- [x] Come up with consistent list-placement API across pins, macros, nets (revisit TCL code from Andreas)
- [x] Change how units are handled (#229)
- [x] Add place_nets function based on above API (#238)
- [x] Basic docs/"pre-ZeroSoC" example so Andreas can get started using it!

Post-meeting todos:
- [x] Remove OpenROAD floorplan integration/schema item
- [x] Separate CLI entry point to quickly iterate/visualize results
- [x] Remove cell dictionary abstraction
- [x] Read mfg grid/db units from tech lef
- [x] Modify `create_die_area` API to support rectilinear dies/cores
- [x] Document/clean up newer functions
- [x] Fix obs vs blockage, make both functions more powerful
- [x] Add direction argument to `fill_io_region`
- [x] Figure out if we can simplify via specifications
- [x] Add `snap` arg to `place_vias`
- [ ] Higher-level functions for powerring stuff
    - [x] Vias @ intersections
    - [x] Ring
    - [ ] Grid
    - [x] Figure out how to automate vias to power stripes
- [x] Clean up/test LEF parsing refactor
